<?php
$arr = [
    "Home",
    "About Us",
    "Services",
    "Blog",
    "FAQ",
    "Contact",
    "Plan",
    "Login",
    "Logout",
    "Sign up",
    "Copyright",
    "All Rights Reserved",
    "Username",
    "Email Or Username",
    "Password",
    "Remember Me",
    "Forgot password?",
    "Don't have any account? Sign Up",
    "SIGN UP FORM",
    "Sponsor By",
    "First Name",
    "Last Name",
    "Email Address",
    "Your Phone Number",
    "Confirm Password",
    "Already have an account? Login",
    "Please confirm your password before continuing.",
    "Forgot Your Password?",
    "Already have an account?",
    "Reset Password",
    "Enter your Email Address",
    "Don't have an account?",
    "Send Password Reset Link",
    "New Password",
    "403 Forbidden",
    "You don’t have permission to access ‘/’ on this server.",
    "Back To Home",
    "Sorry page was not found!",
    "We're sorry, the page you requested could not be found. Please go back to the homepage or contact us at",
    "Method not allowed",
    "opps!",
    "Session has expired",
    "Dashboard",
    "Invest History",
    "Add Fund",
    "Fund History",
    "Transaction",
    "Payout",
    "Payout History",
    "My Referral",
    "Referral Bonus",
    "Profile Settings",
    "Support Ticket",
    "Main Balance",
    "Interest Balance",
    "Total Deposit",
    "Total Earn",
    "Account Statistics",
    "Total Invest",
    "Total Payout",
    "Total Ticket",
    "Total Referral Bonus",
    "Latest Registered Partner",
    "The last Referral Bonus",
    "Email",
    "Phone Number",
    "Joined At",
    "Code",
    "Pay Now",
    "Payment By",
    "Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Google Authenticator",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Close",
    "Verify",
    "Verify Your OTP to Disable",
    "Transactions",
    "Search for Transaction ID",
    "Remark",
    "Search",
    "SL No.",
    "Transaction ID",
    "Amount",
    "Remarks",
    "Time",
    "Type Here",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Gateway",
    "Charge",
    "Search Service",
    "Subject",
    "Image Upload",
    "Upload",
    "Last Reply",
    "Reply",
    "Open",
    "Answered",
    "Customer Reply",
    "Closed",
    "Upload File",
    "Confirm",
    "Are you want to close ticket?",
    "My Profile",
    "Open Ticket",
    "Show Ticket",
    "No Data found",
    "Email Verification",
    "Update User",
    "Update Password",
    "Admin Feedback",
    "PAYOUT NOW",
    "Transaction Limit:",
    "Payout By",
    "Remove",
    "Confirm Now",
    "Return Interest",
    "Received Amount",
    "Upcoming Payment",
    "Search User",
    "Bonus From",
    "Current Password",
    "Address",
    "Submit",
    "Useful Links",
    "Deposit Balance",
    "2FA Security",
    "Referral Link",
    "Level",
    "Back",
    "Make A Deposit",
    "deposit history",
    "bet history",
    "Support Tickets",
    "Withdraw Funds",
    "payouts history",
    "invite friends",
    "2FA Security",
    "personal profile",
    "Result",
    "1",
    "2",
    "X",
    "2X",
    "3X",
    "More",
    "Live Matches",
    "See More",
    "All Sports",
    "All markets",
    "bet slip",
    "my bets",
    "Your Bets",
    "Default checkbox",
    "Checked checkbox",
    "save changes",
    "Overall Odds",
    "Maximum stake amount",
    "Charge Apply",
    "Potential Winnings",
    "place bet",
    "Quick Links",
    "About",
    "OUR Services",
    "subscribe newsletter",
    "Enter Email",
    "Login here",
    "sign in",
    "Create account",
    "Join us",
    "Last name'",
    "Email address",
    "Select Code",
    "Make a deposit",
    "withdraw funds",
    "invite friends",
    "personal profile",
    "You have no notifications",
    "Join",
    "Sports",

    "Bet Slip",
    "Previous",
    "Bet History",
    "Invest Amount",
    "Return Amount",
    "Ratio",
    "Status",
    "Information",
    "No Data Found!",
    "Match Name",
    "Category Name",
    "Tournament Name",
    "Question Name",
    "Option Name",
    "Processing",
    "Win",
    "Refunded",
    "Latest 10 Results",
    "Name",
    "Your Card Information",
    "Enter your card number",
    "Enter the name on your card",
    "Warning",
    "Uh-ho! We are unable to process your Payment by this method.",
    "This method is under construction!!",
    "Select",
    "as your payment method.",
    "Payment Preview",
    "SCAN TO SEND",
    "To Get",
    "Pay Now",
    "Please follow the instruction below",
    "You have requested to deposit",
    "for successful payment",
    "Please Pay",
    "Pay with VoguePay",
    "Detail",
    "Details",
    "Request Amount",
    "Charge Amount",
    "Total Payable",
    "Available Balance",
    "Additional Information To Withdraw Confirm",
    "Image Update",
    "Password Setting",
    "Identity Verification",
    "Address Verification",
    "Select Language",
    "You previous request has been rejected",
    "Identity Type",
    "Your KYC submission has been pending",
    "Your KYC already verified",
    "You previous request has been rejected",
    "Address Proof",
    "Select Image",
    "Change",
    "Enter Subject",
    "Enter Message",
    "Create Ticket",
    "Action",
    "Amount",
    "2 Step Security",
    "Total Balance",
    "Total Bet",
    "Bet Win",
    "Payment",
    "Plan Name",
    "Next",
    "Referral link",
    "Automatically top up your account balance by sharing your referral link, Earn a percentage of whatever plan your referred user buys.",
    "Referral Members",
    "Mobile",
    "Admin",
    "House",
    "Email",
    "Phone",
    "just drop us a line",
    "Full name",
    "Your message",
    "submit",
    "Live",
    "Upcoming",
    "results",
    "Forbidden",
    "You don't have permission to access ‘/’ on this server",
    "The page you are looking for was not found.",
    "Sorry, your session has expired",
    "Internal Server Error",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
    "Account Recover",
    "back to home",
    "Recover password",
    "Reset your Password",
    "2 step Verification",
    "2 FA Code",
    "Email Verification Code",
    "Resend Code",
    "Sms Verification Code",
    "Register",
    "create an account",
    "register here",
    "Sponsor Name",
    "Email address",
    "Password",
    "Verify Your Email Address",
    "A fresh verification link has been sent to your email address.",
    "Before proceeding, please check your email for a verification link.",
    "If you did not receive the email",
    "click here to request another",

];
return $arr;
